name: Generate Pipeline

on:
  push:
    branches:
      -  development
      -  test

jobs:
  generate-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests jinja2 pathlib aixplain

      - name: Run generate.py to create pipeline.py
        working-directory: aixplain/modules/pipeline
        env:
          BACKEND_URL: ${{ github.ref == 'refs/heads/development' && 'https://dev-platform-api.aixplain.com' || 'https://test-platform-api.aixplain.com' }}
          MODELS_RUN_URL: https://test-models.aixplain.com/api/v1/execute
          TEAM_API_KEY: ${{ secrets.TEAM_API_KEY }}
        run: |
          python generate.py

      - name: Commit and push changes if pipeline.py is updated
        working-directory: aixplain/modules/pipeline
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain pipeline.py)" ]; then
            git add pipeline.py
            git commit -m "Update pipeline.py via GitHub Actions"
            git push origin ${{ github.ref_name }}
          fi
